export enum QUERY_KEYS {
  // AUTH KEYS
  CREATE_USER_ACCOUNT = "CREATE_USER_ACCOUNT",
  SIGN_OUT = "SIGN_OUT",
  SIGN_IN = "SIGN_IN",

  // USER KEYS
  GET_CURRENT_USER = "GET_CURRENT_USER",
  GET_USERS = "GET_USERS",
  GET_USER_BY_ID = "GET_USER_BY_ID",

  // POST KEYS
  GET_POSTS = "GET_POSTS",
  GET_INFINITE_POSTS = "GET_INFINITE_POSTS",
  GET_RECENT_POSTS = "GET_RECENT_POSTS",
  GET_POST_BY_ID = "GET_POST_BY_ID",
  GET_USER_POSTS = "GET_USER_POSTS",
  GET_FILE_PREVIEW = "GET_FILE_PREVIEW",
  CREATE_POST = "CREATE_POST",
  EDIT_POST = "EDIT_POST",
  LIKE_POST = "LIKE_POST",
  SAVE_POST = "SAVE_POST",
  DELETE_SAVE_POST = "DELETE_SAVE_POST",
  DELETE_POST = "DELETE_POST",

  //  SEARCH KEYS
  SEARCH_POSTS = "SEARCH_POSTS",
}